### ISSUE TITLE
Only showing one hotend

### ISSUE THREAD

**Issue by albinger** [kennethjiang/OctoPrint-Anywhere#10]
My machine has 2 hotends.  Only one is showing up and not the one I actively use.

**Comment by kennethjiang** [comment]
@albinger thank you for submitting this issue. I'm aware of this shortcoming of my plugin. However, my own 3D printer only has 1 hotend so it'll be tricky for me to test it even if I could code it up. Any chance you can collaborate with me on it?

**Comment by albinger** [comment]
Certainly.

Let me know what to look for / send your way.

-Andrew

**Comment by kennethjiang** [comment]
Can you email/google hangout me at kenneth dot jiang at gmail dot com ? I'd like to quickly chat with you to figure out what needs to happen to support dual hotends and how you can help.

**Comment by kennethjiang** [comment]
@albinger Will you be able to work with me to look at how to extract data for the 2nd hotend?

**Comment by kennethjiang** [comment]
@albinger This feature should be available now. Let me know if it works for you.
