### ISSUE TITLE
Octoprint anywhere "installed unknown" and cannot see in plugins

### ISSUE THREAD

**Issue by Scintilladist** [kennethjiang/OctoPrint-Anywhere#100]
Using OctoPrint 1.3.11 and using the plugin manager to install OctoPrint-Anywhere the install goes fine with no errors. When it is done, a dialog comes up saying 'Installed: unknown' and when the reboot of the OctoPrint service is done, the OctoPrint-Anywhere doesn't show up under the tool menu. When I go to install it again, it sees that it was already installed and does a 'force' install, yet it still shows as 'Installed: unknown' and when rebooted, nothing shows up.
<img width="909" alt="Screenshot 2019-08-28 at 10 00 17 PM" src="https://user-images.githubusercontent.com/11362243/63874515-4ab86800-c9df-11e9-8f3a-a1d96c555eb8.png">

**Comment by Scintilladist** [comment]
Yes here they are.
[octoprint.log](https://github.com/kennethjiang/OctoPrint-Anywhere/files/3553477/octoprint.log)
[plugin_pluginmanager_console.log](https://github.com/kennethjiang/OctoPrint-Anywhere/files/3553478/plugin_pluginmanager_console.log)

**Comment by kennethjiang** [comment]
It is the same problem as this issue: https://github.com/kennethjiang/OctoPrint-Anywhere/issues/97

Please try the solution in that issue and let me know if it works for you.

**Comment by Scintilladist** [comment]
Thank you so much @kennethjiang . It works perfectly now. Sorry about the trouble.
