### ISSUE TITLE
No setup wizard

### ISSUE THREAD

**Issue by SonBroku** [kennethjiang/OctoPrint-Anywhere#105]
As the title says, I'm not getting a setup wizard as well as it's not showing up in the plugin menu. It shows as installed and enabled, but there's no type of menus or anything for it.

[octoprint(1).log](https://github.com/kennethjiang/OctoPrint-Anywhere/files/3650268/octoprint.1.log)

Here's my log. I already tried several of the other fixes in previous issues. I'm thinking It might also be a dependency issue, but  I can't seem to figure this out.

**Comment by kennethjiang** [comment]
@SonBroku Thank you for reporting the problem.

For your log file it seems that OctoPrint Anywhere's config file is somehow corrupted. You can reset the config file with these steps:

1. SSH to your Raspberry Pi.
2. Delete `/home/pi/.octoprint/data/anywhere/.config.yaml`
3. Restart OctoPrint. Once the OctoPrint restarts you should see the wizard. Let me know if that's not the case.

**Comment by SonBroku** [comment]
That worked. I also had installed the polar cloud plugin last night after i made this post, and I had to delete it as well before it would work. Thanks.
