### ISSUE TITLE
Octoprint anywhere doesnt show in plugins 

### ISSUE THREAD

**Issue by davidjau34** [kennethjiang/OctoPrint-Anywhere#107]
Hello! I trying to install octoprint anywhere on my octo print version 1.3.11 but after installing and the necessaries restart the setup wizard doesn't show up

**Comment by kennethjiang** [comment]
Very possibly this is caused by the same issue as https://github.com/kennethjiang/OctoPrint-Anywhere/issues/102 . Can you post `octoprint.log` file here so that I can take a look at it?

**Comment by davidjau34** [comment]
[octoprint.log](https://github.com/kennethjiang/OctoPrint-Anywhere/files/3732246/octoprint.log)
There it is

**Comment by kennethjiang** [comment]
Confirmed it's the same issue as #102 

The fix is to ssh to your Pi and run:
`/home/pi/oprint/bin/python -m pip install backoff==1.6.0`

It should work after you restart OctoPrint. Let me know if otherwise.

**Comment by davidjau34** [comment]
now its show but after a couple of restarts the setup wizard doesn't appear 
[octoprint(1).log](https://github.com/kennethjiang/OctoPrint-Anywhere/files/3732628/octoprint.1.log)

**Comment by kennethjiang** [comment]
It looks like in your case there were 2 packages (maybe more) missing. Please run this on your Pi:

`/home/pi/oprint/bin/python -m pip install raven==6.9.0`

**Comment by davidjau34** [comment]
It finally works out! thanks, man!
