### ISSUE TITLE
Feature request: Livestream / Camera view for "guests"

### ISSUE THREAD

**Issue by unixb0y** [kennethjiang/OctoPrint-Anywhere#15]
I have a feature request:
Maybe with a "guest account" or so, friends can watch the Camera without having access to the "Pause" and "Stop" buttons?
That would be awesome! 
Thank you for your great work 👍 #

**Comment by kennethjiang** [comment]
Yup this'd be a very useful feature! thank you for proposing that.

2 ways to implement it comes to my mind:
* Add a button to make the cam feed public. anyone who has the correct link can watch the cam feed. Very similar to google drive's function of **sharing as a link**.
* Invite your friends to sign up with their email. You can control what they can see/do on a 'settings' page.

Which one you think will work better for you?

**Comment by unixb0y** [comment]
I would do it with sharing a link 😊
The user would have a link associated to his printer / his account and he can toggle it on / off :)
What do you think?

**Comment by kennethjiang** [comment]
@unixb0y This feature has been implemented in latest version and it's working quite well. Please check it out.

**Comment by unixb0y** [comment]
Thank you very much 😊
Already seen it, but both my printer and my Pi are currently not working / broken unfortunately :(
I'll try it as soon as they're back working again.. :)
