### ISSUE TITLE
Feature Request: Reduce time between snapshots

### ISSUE THREAD

**Issue by modem7** [kennethjiang/OctoPrint-Anywhere#19]
Heya, 

It seems that the plugin updates every ~5 seconds between camera snapshots. Is it possible to have a choice of the refresh duration (e.g. a dropdown or input box)?

**Comment by kennethjiang** [comment]
Yes it's on the roadmap!

**Comment by kennethjiang** [comment]
One question though: do you want the refresh rate to be adjustable, or you just want higher refresh rate? The latter is easier to implement, but will cost higher data rate (it may or may not matter for the people with limited mobile data plan)

**Comment by kennethjiang** [comment]
@modem7 I increased the frame rate to 5Hz but then the backend service was overwhelmed. Now I temporarily reduced the frame rate to 0.5Hz. After I optimized the backend service, I will bump it up again.

i also implemented a toggle on dashboard so that you can switch on "bandwidth saving mode".
