### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jslick007** [kennethjiang/OctoPrint-Anywhere#23]
Custom names for printers instead of "My First 3D Printer". Minor I know, but would be helpful as I have 2 Prusa Mk2s connected, one with an MMU and it's sometimes confusing as to which one I'm viewing.

**Comment by kennethjiang** [comment]
You can now change the printer name by clicking the 3 dots on the right, and clicking 'Preferences'. Let me know if you run into any problems.

**Comment by jslick007** [comment]
Confirmed working! Awesome!
