### ISSUE TITLE
Flip / Rotate Camera feature

### ISSUE THREAD

**Issue by NTX9** [kennethjiang/OctoPrint-Anywhere#30]
Is it possible to add some code to allow the camera to be rotated 180 degrees?

**Comment by kennethjiang** [comment]
@NTX9 I think you can get 180-degree rotation by checking both "Flip Horizontally" and "Flip Vertically". But I could be wrong 'coz I'm not very good with maps and directions. ;)

**Comment by kennethjiang** [comment]
@NTX9 I'm closing this issue assuming the solution I proposed worked for you. Please re-open it if it was not the case.
