### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by olemah** [kennethjiang/OctoPrint-Anywhere#35]
Still getting application error when logging in to getanywhere.io

**Comment by kennethjiang** [comment]
The hosting service had an unscheduled outage. It looks like they are just back online. But I won't be surprised if it will still take them a while to stabilize the system. Sorry for that @olemah

**Comment by kennethjiang** [comment]
it looks like the hosting service has stabilized now. I'm closing this issue. But feel free to reopen it if the app goes down again. @olemah
