### ISSUE TITLE
Waiting for Camera Feed

### ISSUE THREAD

**Issue by strongbow1** [kennethjiang/OctoPrint-Anywhere#43]
After registering my camera I only get waiting for camera feed. But my Camera works fine within Octoprint

**Comment by kennethjiang** [comment]
Sorry I was just back from vacation.

Do you know how you to get access to OctoPrint log files? If so, can you zip up those log files and post them here or send them to me at kenneth dot jiang at gmail dot com? @strongbow1

**Comment by strongbow1** [comment]
Hi kenneth

Thank you for your reply. Sorry I do not know how to access the Octoprint log files. If you tell me how to get them I will get them for you.

Mit Freundlichen Grüsse
With Best Regards
Sandro Strimer

**Comment by strongbow1** [comment]
Hi Kenneth

I got it working again.

Just reinstalled octoprint on my raspi. That solved it for now

Thank you again for your help and fast response

Mit Freundlichen Grüsse
With Best Regards
Sandro Strimer

**Comment by kennethjiang** [comment]
You are welcome! I'm glad that you figured this out.
