### ISSUE TITLE
No such app

### ISSUE THREAD

**Issue by Stellarspiff** [kennethjiang/OctoPrint-Anywhere#44]
It stopped allowing me to view the Octoprint Anywhere page. Sends me to a Heroku page that says "There's nothing here, yet."

**Comment by kennethjiang** [comment]
shoot there is an outage on the backend. working on that!

**Comment by Stellarspiff** [comment]
Thanks for the update!

**Comment by johnpettybone** [comment]
Same problem. Eta? :)

**Comment by kennethjiang** [comment]
Sorry it's quite a nasty backend issue. Will take a while. working on it but can't provide an eta now...

**Comment by kennethjiang** [comment]
@Stellarspiff @johnpettybone I restored the backend service. However it requires up to 24 hours to get the new DNS to propagate. Please let me know if you still can't access the Dashboard after 24 hours. Sorry for the trouble!

**Comment by kennethjiang** [comment]
It looks like the backend is restored for most users around the world. Closing this issue.
