### ISSUE TITLE
Webcam feeds not showing up

### ISSUE THREAD

**Issue by cptprime** [kennethjiang/OctoPrint-Anywhere#46]
i have 7 identical printers all running their own Pi/octopi setup, i thought i would be smart and have yawcam streaming a single webcam across the local network to all the octopis, it works well via octopi but on the dashboard it gets stuck on "Waiting for camera feed..."

**Comment by kennethjiang** [comment]
Hi @cptprime thank you for submitting the issue.

Do you have 7 OctoPrints (7 Rasperry Pis), or only 1? 

I'm not familiar with yawcam. Can you provide a little more info on how the yawcam is connected to Raspberry Pi(s)?

**Comment by cptprime** [comment]
Hi @kennethjiang i have indeed 7 raspberry Pis, yawcam just serves my webcam as a stream on the local network, it also lets me do timelapse from within octoprint.

i just point octoprint's webcam adress from 127.0.0.1 to what ever the adress of yawcam is

**Comment by kennethjiang** [comment]
Ah I understand now.

I just checked and yawcam and it is a MJPEG server. Assuming yawcam can be displayed correctly in the `Control` tab in OctoPrint, I can't think of a reason why it wouldn't work with OctoPrint Anywhere. 

Do you install OctoPrint Anywhere on all OctoPis, or just one of them?

**Comment by kennethjiang** [comment]
Hi @cptprime  I'm cleaning up old issues. Do you still experience this issue? If not I'd like to close it.
