### ISSUE TITLE
Full screen webcam?

### ISSUE THREAD

**Issue by Quintin9801** [kennethjiang/OctoPrint-Anywhere#47]
A full screen webcam feature would be amazing, I’m currently just zooming in on the image but this enhancement would be nice!

**Comment by kennethjiang** [comment]
Very good suggestion! Will get to it at some point!

**Comment by Quintin9801** [comment]
Awesome! Thank you so much

**Comment by JD2005L** [comment]
Came here to ask for the same, would be very useful.  Double click video for fullscreen, for example, similar functionality to Octoprint-Fullscreen plugin: https://github.com/BillyBlaze/OctoPrint-FullScreen

**Comment by kennethjiang** [comment]
Thx @JD2005L  I will take a look at that plugin to see how it's implemented

**Comment by kennethjiang** [comment]
@JD2005L @Quintin9801 full screen turns out to be non-trivial to do. But now the image is zoomable (https://github.com/kennethjiang/OctoPrint-Anywhere/issues/54). I hope this at least solve part of your problem.

**Comment by JD2005L** [comment]
Yep works for me.  Thanks!

**Comment by kennethjiang** [comment]
@JD2005L The new 25fps video streaming will go full screen on a tap. Closing this issue.
