### ISSUE TITLE
Deleting timelapses?

### ISSUE THREAD

**Issue by cristianefe** [kennethjiang/OctoPrint-Anywhere#52]
Hello! Is there any way to delete timelapses?

**Comment by kennethjiang** [comment]
There is currently no way to delete timelapses. I will add this feature whenever I get a chance to work on it.

**Comment by kennethjiang** [comment]
@cristianefe Just added the function to delete timelapse. Just refresh the time lapse page you will see it. No plugin upgrade is needed.
