### ISSUE TITLE
[Feature Request] Zoomable Video feeds

### ISSUE THREAD

**Issue by devsfan1830** [kennethjiang/OctoPrint-Anywhere#54]
In order to be able to catch any fine print errors via the feed that we might want to stop I think it would be nice if the website supported the pinch/spread to zoom in and out to resize/stretch the video window. Similarly, it would be nice be able to fullscreen stretch the feed on a desktop browser.

**Comment by kennethjiang** [comment]
@devsfan1830 Now the page is zoomable. You can just head to the dashboard and refresh the page. No plugin upgrade is needed.
