### ISSUE TITLE
More than one Printer in Dash

### ISSUE THREAD

**Issue by ManuelW77** [kennethjiang/OctoPrint-Anywhere#6]
Hey there,

i registered today me and my printer, but i have in my Dash 7 more printers that in active and not mine.
I can't delete or remove them.

**Comment by kennethjiang** [comment]
Thank you for reporting this issue. Apparently other users experience the same. It's a glitch in my software. I'm actively working on this issue and will keep you posted with the progress.

**Comment by kennethjiang** [comment]
I just fixed the issue. Please come back to [OctoPrint Anywhere dashboard](https://www.getanywhere.io/app/devices) to see how it works for you. @buffalowolff
