### ISSUE TITLE
Feature request: zoom in function for video feed

### ISSUE THREAD

**Issue by Quas7** [kennethjiang/OctoPrint-Anywhere#60]
Hi,

in order to check for first layer quality remotly it would be great to have a "zoom in" together with a "pause video" or "shoot still image" function. Together with a babystepping G-code sending option a fine tuning of the first layer would then be possible (https://github.com/kennethjiang/OctoPrint-Anywhere/issues/59).

Best,
Quas7

**Comment by kennethjiang** [comment]
In OctoPrint Anywhere 1.0 the webcam feed will go fullscreen if you tap on it.
