### ISSUE TITLE
The way to get current IP address is not compatible with Windows

### ISSUE THREAD

**Issue by kennethjiang** [kennethjiang/OctoPrint-Anywhere#66]
It results in errors: `hostname -s is not supported`.

**Comment by rickgode** [comment]
Did you fix this?  I didn't notice all those errors in the latest release.  I'm guessing so?

Ricky

**Comment by kennethjiang** [comment]
Did fix it. Forgot to close it. :)

**Comment by modiyagya** [comment]
Hi, how did you fix "hostname -s is not supported" in windows 10?
