### ISSUE TITLE
No camera 

### ISSUE THREAD

**Issue by greg-wood** [kennethjiang/OctoPrint-Anywhere#67]
I am not getting any camera feed either when idle or printing. I am using the multicam plugin, not sure if that might be the issue.

![image](https://user-images.githubusercontent.com/35552379/46328142-22579c00-c5cb-11e8-8d0a-c3597bf4a3b3.png)

**Comment by kennethjiang** [comment]
It's possible that OA is not compatible with MultiCam plugin. Will investigate it.

**Comment by kidwon13** [comment]
I have a similar issue. My OA webcam feed was working and now it's not. I run my webcam on Yawcam connected to a pc. The feed is still working normally in Octoprint, I can access it fine with a browser and I also have the feed set up in Blue Iris and it works okay there too but since yesterday I no longer see it in OA.

**Comment by kennethjiang** [comment]
@kidwon13 Are you also using MultiCam plugin?

**Comment by kidwon13** [comment]
No I am not. It also started working when I started printing. It just wasn't displaying while idle.

**Comment by kennethjiang** [comment]
The cam feed has longer lag when printer is idle to save bandwidth. But if you wait, say more than 30 seconds and the cam feed is still not coming up, then I'm pretty sure it indicates some bug in the code. Will be happy to dig deeper if that's the case.

Can you send me the `octoprint.log` file?

**Comment by kidwon13** [comment]
[octoprint.log](https://github.com/kennethjiang/OctoPrint-Anywhere/files/2442743/octoprint.log)

**Comment by kennethjiang** [comment]
Hi @kidwon13 It looks like the wifi network your OctoPi is on has sporadic connectivity issues. For instance, OctoPrint Anywhere couldn't reach to internet during the periods of 2018-10-02 21:34 - 2018-10-02 21:38 (GMT), 2018-10-03 05:30 - 2018-10-03 05:34. There were also times when the Yawcam couldn't be reached.

Next time when you lose the cam feed, can you SSH to your OctoPi to check if it has connectivity to the internet and yamcam server?

**Comment by kidwon13** [comment]
I seem to still be losing webcam access when the printer is idle. I did ssh into my raspberry pi and I can ping an internet ip address no problem (I used 4.2.2.2 for my test). Even while I was pinging I did not have the webcam feed on getanywhere.io but I do see it both in the web access to yawcam and on the control tab of octoprint.  I think the wi-fi outages you saw were when I was making configuration changes on my router.  
Curiously I tried to configure a similar setup for my step-dad and he never sees his camera feed on getanywhere.io. It shows his temperatures and status correctly but no webcam feed. I also pinged out from his raspberry pi and it seems to be working okay but he did have a little more packet loss than I did. About 1% over 3 or 4 minutes. 
I'll attach both of our current octoprint.log files. 
[StepDad_octoprint.log](https://github.com/kennethjiang/OctoPrint-Anywhere/files/2444265/StepDad_octoprint.log)
[My_octoprint.log](https://github.com/kennethjiang/OctoPrint-Anywhere/files/2444266/My_octoprint.log)

**Comment by kennethjiang** [comment]
Thanks a lot @kidwon13  for the detailed info. It sounds like we need a screen sharing session to debug further.

Can you send me email at kenneth dot jiang at gmail dot com to coordinate a time?

**Comment by kennethjiang** [comment]
@greg-wood I installed MultiCam myself and it still works.

@kidwon13 helped me find a bug in the cam feed code (thank you @kidwon13!). Just fixed it and released 0.8.5 for that.

Can you upgrade to 0.8.5 to see if that solves your problem too. If not, can you post the screenshots of your webcam config and MultiCam config page (I posted the screenshots for my configuration as examples)?

<img width="1440" alt="screen shot 2018-10-03 at 5 11 33 pm" src="https://user-images.githubusercontent.com/779786/46446166-8eebab80-c72f-11e8-88b2-b5a7fbbef2de.png">
<img width="1440" alt="screen shot 2018-10-03 at 5 11 26 pm" src="https://user-images.githubusercontent.com/779786/46446167-8eebab80-c72f-11e8-96eb-807e99ee36d0.png">

**Comment by kennethjiang** [comment]
Closing it with the assumption that it's fixed.
