### ISSUE TITLE
Seeing many empty streams

### ISSUE THREAD

**Issue by buffalowolff** [kennethjiang/OctoPrint-Anywhere#7]
I am seeing my own printer in a list of many many blank ones.  Any thoughts?
<img width="1842" alt="capture" src="https://user-images.githubusercontent.com/21088809/27791645-175b62f0-5fc4-11e7-8ec8-d9dfb00349c3.PNG">

**Comment by kennethjiang** [comment]
Thank you for reporting this issue. Apparently other users experience the same. It's a glitch in my software. I'm actively working on this issue and will keep you posted with the progress.

**Comment by kennethjiang** [comment]
I just fixed the issue. Please come back to [OctoPrint Anywhere dashboard](https://www.getanywhere.io/app/devices) to see how it works for you. @buffalowolff
