### ISSUE TITLE
Feature Request: Improve Movement commands

### ISSUE THREAD

**Issue by Delta-38** [kennethjiang/OctoPrint-Anywhere#70]
I really like Octoprint-Anywhere, however I find that the movement commands could be improved, 
when I first installed Octoprint to manage my printer I instantly fell in love with the scalable movement approach of the Control tab, where moves can be set with scale. 
So I think it would be very nice if you could add movement scale 1/10/100mm on the various axes.
More importantly though, sometimes moving the axes can be tricky to get right because there is no feedback as to if the command has been received and/or is being processed, or even if they are enqueueable, I think it could be improved if a) a command being processed caused a temporary visible lock of the control, or b) if the processing was shown somehow.

What do you think?

**Comment by kennethjiang** [comment]
Thank you @Delta-38 for making a very detailed suggestion. And sorry for the delay in my response.

I agree with most of what you said. But I have a different opinion on the variable movement scale (1/10/100mm). 2 problems that I have with that interface are: 1) It requires more finger/mouse movements and clicks, and 2) Quite often I didn't notice the scale was on 100mm when I clicked the up arrow on Z, and oops - I had to patiently watch Z to slowly move up 100mm and then bring it back down equally slowly. Have you also found these 2 things problematic?

On a different note: do you use the OA's xyz movement when you are remote, or when you are next to the printer? The reason why I ask this question is I have been struggling to decide if it's necessary to have the webcam feed shown right above the buttons.

**Comment by Delta-38** [comment]
Sorry for the delay, I didn't see the notification :)
Regarding the scale of movement yes, I understand what you are saying, and sometimes that happens to me too, however my workflow with the remote (After the end gcode parks the bed forwards and the extruder on the X endstop) is usually just shifting the head and plate so as to nudge the completed part down to the side, so I don't usually raise the print head at all.
I usually use OA's remotely, whereas if I am in the house I usually use the Control view in octoprint. Having the webcam and the controls in the same view is quite practical to me. 
Otherwise I would probably end up using TeamViewer to access a local machine and use the local interface, 
Do you think a shorter but still "a bit more than 10mm movement scale" could be implemented?
Mostly because usually if coupled with the relative lag of the webcam feed, it can be a full minute of tap... wait... be sure... tap again... to complete just a couple of traverses of X and Y axes.
(In the long run I'll probably print a small robot arm to nudge stuff off the plate but so far OA has been priceless and for monitoring it is a really useful tool)

**Comment by kennethjiang** [comment]
Hah it's a very creative way to knock off part using print head. I've heard people talk about this idea but you are the only one I know of who is really doing this. :)

Although I use OA to move nozzle even if I'm next to the printer, I suspect most users are like you - use OA only when they are remote, what you suggested make a lot of sense.

I will think about if/how I can redesign the nozzle movement page to make it less painful when used remotely.

**Comment by kennethjiang** [comment]
@Delta-38 In OctoPrint Anywhere 1.0 the control is a lot more responsive now as the webcam feed will send a burst of frames if you tap on a button. This doesn't completely solve your problem but should make it less painful.

Since not a lot of users requested this feature, I'm closing it for now. Feel free to re-open it if you feel strongly about it.
