### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by dataman** [kennethjiang/OctoPrint-Anywhere#8]
Receiving an: Internal Server Error when attempting to register using facebook credentials.
Call back string was: https://www.getanywhere.io/pub/link_printer?token=VCSPW74M9BDFMQFKX7ZIUGPJGBC34N1R

**Comment by kennethjiang** [comment]
Hi @dataman sorry that you ran into issue with this plugin.

Can you please email me at kenneth dot jiang at gmail dot com ? I need to ask for additional info to further diagnose the problem.

**Comment by dataman** [comment]
Sure, I'll give it another try and email you.  Sorry it's been so long.  I gave up.
