### ISSUE TITLE
file does not exist.

### ISSUE THREAD

**Issue by caninjpn** [kennethjiang/OctoPrint-Anywhere#86]
I installed Octoprint and was trying to install Octoprint Anywhere from the plugin manager but it's gave an error saying

> Invalid requirement: 'pip install "https://github.com/kennethjiang/OctoPrint-Anywhere/archive/master.zip"'
> It looks like a path. File 'pip install "https://github.com/kennethjiang/OctoPrint-Anywhere/archive/master.zip"' does not exist.
> Error!
> Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

I'm not sure why this error occurred as the path is correct.

**Comment by kennethjiang** [comment]
I'm puzzled too. The path indeed was correct. Are you running OctoPrint on a Raspberry Pi or a PC?

**Comment by caninjpn** [comment]
> I'm puzzled too. The path indeed was correct. Are you running OctoPrint on a Raspberry Pi or a PC?

I'm running on a Raspberry Pi 3B+.
Aside from setting up I had to install a hotfix so the OctoPrint could communicate with my Monoprice Select Mini. I'm not sure if this will help but that's the only thing I can think of that may cause this problem.

**Comment by kennethjiang** [comment]
Can you ssh to your Pi and run `/home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install https://github.com/kennethjiang/OctoPrint-Anywhere/archive/master.zip --no-cache-dir --process-dependency-links` manually to see if you are getting the same error?

**Comment by kennethjiang** [comment]
Closing this issue since there haven't been any reports recently on this issue. It sounds like a temporary issue during the time when OctoPrint 1.3.11 was officially released.
