### ISSUE TITLE
Camera feed cannot be rotated or flipped

### ISSUE THREAD

**Issue by ChrisCrewdson** [kennethjiang/OctoPrint-Anywhere#9]
My printer's camera is mounted upside down (like this https://www.thingiverse.com/thing:1646474). I have the "Flip webcam horizontally" and "Flip webcam vertically" options checked in OctoPrint.
If these settings can be read from the API, they should determine parameters sent to mjpg_streamer for rotation (or elsewhere as appropriate in the chain).

**Comment by kennethjiang** [comment]
Thanks @ChrisCrewdson for proposing this feature. It's definitely on my roadmap. Will keep you posted when i get it implemented.

**Comment by cwestpha** [comment]
Ideally, could it parse the config.yaml file and pull the webcam settings and replicate those? that way it will honor the flips, rotations, and other settings made in octoprint and use those.
http://docs.octoprint.org/en/master/configuration/config_yaml.html#webcam

**Comment by kennethjiang** [comment]
Good point @ChrisCrewdson I was thinking about exactly that. However I ran into a few technical trickiness there. So I eventually implemented a simpler version, which requires you to set it in Anywhere dashboard. However you only need to do it once and it'll remember the setting.

Give it a swing by upgrading OctoPrint Anywhere to 0.2.2 and then heading to Anywhere dashboard. Let me know if you run into any problems.

**Comment by ChrisCrewdson** [comment]
It looks like checking both of them is incompatible.
Having neither checked like this ![capture1](https://user-images.githubusercontent.com/597792/28051960-b1862f42-65bc-11e7-92e1-ccd97ce69a64.PNG)
looks the same as having both checked like this
![capture3](https://user-images.githubusercontent.com/597792/28051975-cae75696-65bc-11e7-9f41-a9653a4facb0.PNG)
Both work great individually, but unfortunately I need both.

**Comment by kennethjiang** [comment]
hmmm, what browser and OS are you using? how about their versions?

**Comment by ChrisCrewdson** [comment]
This occurs on:
Ubuntu 17.04 with Chrome Version 59.0.3071.86 
Windows 10 with Chrome (latest version)

**Comment by kennethjiang** [comment]
Thank you! Will work on it!

**Comment by kennethjiang** [comment]
Just pushed a new release. Please take a look (you don't need to upgrade the plugin. Just log into https://www.getanywhere.io/app/devices ). Let me know if it still doesn't work.

**Comment by ChrisCrewdson** [comment]
It doesn't look like it has changed. I tried all the combination with the same result as above.

**Comment by kennethjiang** [comment]
can you force a refresh in your browser?

**Comment by kennethjiang** [comment]
hold on, found a problem that may still causes a problem in your browser. fixing it now.

**Comment by kennethjiang** [comment]
Now it should be fixed (for real this time). But I will leave this issue open until you confirm it @ChrisCrewdson

**Comment by ChrisCrewdson** [comment]
It works! Thanks for all your attention and quick response on this.
