### ISSUE TITLE
Not showing up in Plugin Manager or launching Setup Wizard

### ISSUE THREAD

**Issue by irmcdermott** [kennethjiang/OctoPrint-Anywhere#90]
I'm brand new, so I apologize if this isn't the right place for this. 

Since I'm new, I've installed the latest version of OctoPi, and I downloaded Octoprint Anywhere from the repository. The on screen dialog says it installed successfully, but the Setup Wizard doesn't open. I tried reinstalling and it tells me that it is already installed but forces a new install. It also is not showing up in my Plugin Manager list, or at the bottom of the left hand column of my settings page with the rest of my installed. Am I doing something wrong?

**Comment by kennethjiang** [comment]
Thank you for submitting this issue report and sorry for the problem you are experiencing.

Can you attach "octoprint.log" to this issue so I can take a look? You can find the log file by following this instruction: https://community.octoprint.org/t/where-can-i-find-octoprints-and-octopis-log-files/299

**Comment by irmcdermott** [comment]
[octoprint.log](https://github.com/kennethjiang/OctoPrint-Anywhere/files/3304278/octoprint.log)

**Comment by kennethjiang** [comment]
Thank you @irmcdermott for sending me the log file. The log file revealed a weird error that seems to be caused by failure in python package management system.

Can you ssh to your OctoPi and run this command and post herewhat you see on the screen?

```
/home/pi/oprint/bin/python -m pip install backoff==1.4.3
```

**Comment by irmcdermott** [comment]
[op anywhere.txt](https://github.com/kennethjiang/OctoPrint-Anywhere/files/3306046/op.anywhere.txt)

**Comment by kennethjiang** [comment]
It looks like python module `backoff` was installed successfully. Can you restart OctoPi and see if OctoPrint Anywhere works correctly now?

**Comment by irmcdermott** [comment]
i restarted and it was showing up in my plugin manager, but not showing up on the left hand column underneath "Plugins" and still not getting any kind of Setup Wizard. Sorry! 
[plugin_pluginmanager_console.log](https://github.com/kennethjiang/OctoPrint-Anywhere/files/3308513/plugin_pluginmanager_console.log)
[octoprint.log](https://github.com/kennethjiang/OctoPrint-Anywhere/files/3308514/octoprint.log)
![Capture](https://user-images.githubusercontent.com/51962892/59814201-0d967200-92da-11e9-8841-cd0824766e48.PNG)

**Comment by kennethjiang** [comment]
Thank you @irmcdermott .

Your new log file shows that it's now failing at another python module. I'm pretty convince that it is caused by a strange python module management bug.

Please ssh to your Pi and run this command `/home/pi/oprint/bin/python -m pip install raven picamera==1.13`. 

These should be the last dependencies that were somehow in corrupted state. After that you restart OctoPi and the OctoPrint Anywhere plugin should work correctly.

**Comment by NeoRame** [comment]
Same Problem here. i tried both commands... 
the result till now, i can see the plugin in the manager, but no wizzards starts and there is no plugi in in the plugin list in the bottom left hand  corner.

[plugin_pluginmanager_console.log](https://github.com/kennethjiang/OctoPrint-Anywhere/files/3312243/plugin_pluginmanager_console.log)
[octoprint.log](https://github.com/kennethjiang/OctoPrint-Anywhere/files/3312244/octoprint.log)

**Comment by NeoRame** [comment]
THANK You, find a solution. uninstalled raven and reinstalled anywhere as you  mentioned here: https://github.com/kennethjiang/OctoPrint-Anywhere/issues/56#issuecomment-437495086

**Comment by kennethjiang** [comment]
Thank you @NeoRame . I already forgot that we ran into similar issues before! Definitely a weird bug in python module management and/or Pi.

**Comment by irmcdermott** [comment]
Thank you to both of you! Appears to be up and running now!
