### ISSUE TITLE
A Space needed in notification email

### ISSUE THREAD

**Issue by phcoetzee** [kennethjiang/OctoPrint-Anywhere#94]
I've noticed that there needs to be a space between: **Yeah! Your print job** and the gcode filename. It makes it sometimes difficult for me to read.

![space_here](https://user-images.githubusercontent.com/38723167/60395715-06702f00-9b38-11e9-9568-a5d82f547d86.jpg)
Thanks

**Comment by kennethjiang** [comment]
Thank you @phcoetzee for reporting this issue. Just fixed it.
