### ISSUE TITLE
PNotify Default Buttons Removed

### ISSUE THREAD

**Issue by FormerLurker** [kennethjiang/OctoPrint-Anywhere#99]
Hi again!  I've gotten some additional reports regarding the removal of the default pnotify confirm buttons, but this time involving Octoprint Anywhere.  I was wondering if you could apply the same fix here as you did to the Spaghetti Detective?  Let me know if/when this is complete and I'll make sure it is tested.

FYI, I'm going to add some code to my confirm dialog that checks for these buttons and will recreate them if necessary, which I think would in turn mess up any plugins that rely on these being removed from the defaults.  I hope that doesn't cause you too many problem!

Thanks!

Brad

**Comment by kennethjiang** [comment]
Ah I forgot that I did the similar thing in OA too. It is really just an easy fix thank to you previous help. The fix is now in new version 1.0.10
